[package]
name = "flatc"
version = "23.5.26"
authors = ["chip <chip@chip.sh>"]
description = "Vendored executable of flatbuffer's `flatc`."
documentation = "https://docs.rs/flatc"
keywords = ["flatbuffers"]
edition = "2018"

[build-dependencies]
cmake = "0.1"
